### ISSUE TITLE
Batches of corrections?

### ISSUE THREAD

**Issue by pronoiac** [fabiensanglard/cpsb#10]
Hey there - 

I skimmed the ebook and annotated it in an app. I have a few dozen notes. Do you have any preferences on how to gather them? Per chapter, maybe? 

I usually write line-per-sentence, for clearer diffs, but that's more likely to get in the way at this point.

**Comment by fabiensanglard** [comment]
My preference is to get one pull request per fix :) ! Thanks for your help!

**Comment by fabiensanglard** [comment]
I meant, one typo fix or or rephrase per PR. Thanks again!
