### ISSUE TITLE
Ki is KiB?

### ISSUE THREAD

**Issue by macias** [fabiensanglard/cpsb#13]
I am not sure if it intended, my only guess is "Ki" is the same as "KiB". If this is the case I would say please stick to "KiB" (and I can find those typos).

*Just to be clear, my preference would be actually old school KB, but I see world moved into other direction :-).*

**Comment by fabiensanglard** [comment]
I am using the international notation in all my books so let's stick to that :) !

Are you referring to usage of "B" in the memory maps?

**Comment by macias** [comment]
For example page 53:
"32 Ki x 16-bit RAM system with two 32 Ki x 8-bit chips"

if this is for KiB IMHO than it should be "KiB" not "Ki".

**Comment by fabiensanglard** [comment]
I am using Ki for Kibi, the kilobinary. Ref: https://physics.nist.gov/cuu/Units/binary.html
