### ISSUE TITLE
Paragraph text describing screenshot is wrong

### ISSUE THREAD

**Issue by MiltosKoutsokeras** [fabiensanglard/cpsb#146]
I have found an error on **Chapter 2 Hardware** (`src/hardware.tex`), section **Draw order and Priority mask**. The paragraph above the screenshot at the bottom describes the following:

```Text
After fighting their way to a busy subway, Haggar and Guy find themselves exiting the train station to continue happily brawling in a desolated part of the city.
```

This is wrong, as the scene in the screenshot is from Level 1: The Slums and the subway scene is in level 2. The scene on the screenshot is after the underground warehouse area and just before the level 1 boss battle.

**Comment by fabiensanglard** [comment]
Changed description to

> Take the example of Final Fight. After fighting their way out of an underground warehouse, Haggar and Guy surface in a desolated part of the city where Damned, the boss of Round 1, awaits them.
