### ISSUE TITLE
Sound "Thread" does not wait for interrupt increased intCounter counter (page 177)

### ISSUE THREAD

**Issue by stefano-leone** [fabiensanglard/cpsb#156]
It seems there is an error in the C code on page 177.

Actually it is:
`while (musCounter < intCounter) {}`

It should be:
`while (musCounter >= intCounter) {}`

Reasoning:
While (musCounter >= intCounter) the main flow actively waits.
It executes one step when the interrupt increments intCounter, that is when musCounter becomes < intCounter.

**Comment by fabiensanglard** [comment]
Fixed in 76ecef54425b3b5e904d06711af5e26283859181
