### ISSUE TITLE
Control "Thread" does not wait for interrupt increased vsync counter (page 195)

### ISSUE THREAD

**Issue by stefano-leone** [fabiensanglard/cpsb#157]
It seems there is an error in the C code on page 195.

Actually it is:
`if (frameCounter < vsyncCounter) continue;`

It should be:
`if (frameCounter >= vsyncCounter) continue;`

Reasoning:
While (frameCounter >= vsyncCounter) the main flow actively waits.
It executes one step when the interrupt increments vsyncCounter, that is when frameCounter becomes < vsyncCounter.

**Comment by fabiensanglard** [comment]
Fixed in 76ecef54425b3b5e904d06711af5e26283859181
