### ISSUE TITLE
Amiga & X68000 Pricing

### ISSUE THREAD

**Issue by WillGreen** [fabiensanglard/cpsb#163]
I love the CP-System book, but was confused by the computer prices in the table on page 208:

* X68000 - $5000
* Amiga 500 - $1500

Page 202 says the price of the X68000 was ¥369,000 or roughly $3000. Which matches the price in Oh!X magazine at the time. 

The Amiga 500 was $699 at launch (source: Wikipedia).

**Comment by fabiensanglard** [comment]
Fixed in 2206c3b3b5976c05231adc17a0d3c9965c1decc2

Thank you for pointing out the mistake.
