### ISSUE TITLE
Incomplete table of contents?

### ISSUE THREAD

**Issue by pronoiac** [fabiensanglard/cpsb#59]
So there are sort of two TOCs: 
* the one on pages 5-11, which is fine, and comprehensive
* the one that appears as bookmarks, in a sidebar or the like, depending on your PDF viewer. this one's only around a dozen items long.

I'm ok with it being fairly brief, but it's missing chapters:
* 3 Software concepts
* 4 GFX System
* 5 Sound System
* 6 Control System

I've poked around a little, but nothing's jumping out at me.

**Comment by fabiensanglard** [comment]
It seems to be a PDF viewer specific issue. I am using `evince` and all sections are there.

**Comment by fabiensanglard** [comment]
Closing until further info is added. Feel free to reopen.

**Comment by pronoiac** [comment]
It's happening in Bluefire Reader on an iPad, but I confirmed that it's working as expected in Preview on a Mac. I'm considering it not our problem to fix.
