### ISSUE TITLE
Images with moire

### ISSUE THREAD

**Issue by guilt** [fabiensanglard/cpsb#63]
Filing that downscaling with a Lanczos filter may help with some of the images on pages 80 and 81.

**Comment by fabiensanglard** [comment]
If you are willing to experiment with it and send a PR, I could gladly consider it. Otherwise, it will stay this way.

**Comment by guilt** [comment]
I guess this happens when images are embededded within the SVG. I tried downscaling only the data/PNG portion of it and it seems to render better. But when put in a SVG, it produces the moire patterns.
![sf2_withoverscan_zero_png_downscaled](https://user-images.githubusercontent.com/195178/193468853-a7dd89a8-3cbc-445e-a0a0-109368f9d14f.png)

**Comment by guilt** [comment]
Further, I tried scaling just the PNG above and the SVG and I could see the side by side differences.

![SxS-Moire](https://user-images.githubusercontent.com/195178/193469060-b827a3a4-3a37-414a-abe2-64038264a5f8.png)

**Comment by guilt** [comment]
Any chance you'd be open to PNGs than SVGs on this one? :)

**Comment by fabiensanglard** [comment]
The image on the left does not show the scanline enough....and the one on the right shows them too much :/ !

**Comment by guilt** [comment]
They are the same image, the one on the right is the SVG version with the one on the left embedded, plus the axes. The scaling for the PNG in SVG does not follow the same rules as the scaling for just PNG.
