### ISSUE TITLE
Mythical CPU

### ISSUE THREAD

**Issue by macias** [fabiensanglard/cpsb#64]
Page 56: "Released in July 1976 by Zilog, the z80 was intended as an Intel 8080 killer thanks to a
compatible instruction set. It ended up becoming an icon of the 70s, sharing the scene
with the equally **mythical** MOS 6502 well into the mid-80s."

I am not native speaker, but to me it does not sound right. Mythical is something well known but not really existing.

IMHO it would be better to use such words as -- legendary, iconic (!) or famous.

**Comment by fabiensanglard** [comment]
Fixed in 798a1079c1485cf99c00be7fcfb0934e1ce1a0de
