### ISSUE TITLE
Reversed bus lines for Z-80

### ISSUE THREAD

**Issue by ajfdez** [fabiensanglard/cpsb#66]
Page 57: ""The bus lines are dedicated D0-D15 for addresses and indicates read while WR indicates a write operation. GND (ground) pins. A0-A7 for data. For control, RD WAIT is used to add wait states."

As it can seen in the image on the book, the Z-80 has only D0-D7 data lines, and A0-A15 for addresses. 

In the text is reversed.  D8-D15 do not exist in that chip.

**Comment by fabiensanglard** [comment]
This was already fixed in 1883c2103d8bbff38e9bc009eba1ac79f978b85d. Thanks for your feedback!
