### ISSUE TITLE
p. 86, unclear caption

### ISSUE THREAD

**Issue by pronoiac** [fabiensanglard/cpsb#83]
> Notice the real estate dedicated to GFXRAM caching

Is that highlighted or anything? Similar on the next page:

> Notice the two parts on the die storing respectively 10 bits and 16 bits.

(Apologies if the diagram in the ebook I'm looking at doesn't reflect the current state of the repo.)

**Comment by fabiensanglard** [comment]
This is the only part that stick out in the die. And this parts clearly has two parts.
